"""Build the Aktiv Grotesk web font CSS.

Writes, relative to the repo root:
  fonts/subset/AktivGrotesk_{Lt,Rg,Bd}.latin.woff2   Latin subsets of three cuts
  fonts/laio-fonts-inline.css                         those subsets as base64 data URIs
  fonts/laio-fonts.css                                all nine full cuts, hosted URLs
  _build/font-test.html                               side-by-side check of both CSS files

  pip3 install fonttools brotli
  python3 _build/build_fonts.py

Safe to rerun. Every output is overwritten, and the same input gives the same bytes.
"""
import base64, html, os, sys
from fontTools import subset

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS=os.path.join(ROOT,"fonts")
SUBSET_DIR=os.path.join(FONTS,"subset")
HOST="https://assets.la.io/fonts/"
INLINE_LIMIT=200_000  # bytes; past this the inline file is too heavy to paste into a page
UNICODES=("U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,"
          "U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD")
# file stem -> (weight, style). The Thin cuts report 275 in OS/2; CSS gets 100, the Thin slot.
CUTS=[("Th",100,"normal"),("ThIt",100,"italic"),
      ("Lt",300,"normal"),("LtIt",300,"italic"),
      ("Rg",400,"normal"),("It",400,"italic"),
      ("SBd",600,"normal"),
      ("Bd",700,"normal"),("BdIt",700,"italic")]
INLINE_CUTS=["Lt","Rg","Bd"]
WEIGHT={stem:w for stem,w,_ in CUTS}

def face(src,weight,style):
    return ("@font-face {\n"
            "  font-family: 'Aktiv Grotesk';\n"
            f"  src: url('{src}') format('woff2');\n"
            f"  font-weight: {weight};\n"
            f"  font-style: {style};\n"
            "  font-display: swap;\n"
            "}\n")

def write(path,text):
    with open(path,"w",encoding="utf-8") as f: f.write(text)

def size(path):
    n=os.path.getsize(path)
    print(f"  {os.path.relpath(path,ROOT):<44} {n:>9,} bytes  {n/1024:7.1f} KB")
    return n

for stem,_,_ in CUTS:
    assert os.path.exists(os.path.join(FONTS,f"AktivGrotesk_{stem}.woff2")), stem

# ---- Latin subsets ----
os.makedirs(SUBSET_DIR,exist_ok=True)
subsets={}
for stem in INLINE_CUTS:
    out=os.path.join(SUBSET_DIR,f"AktivGrotesk_{stem}.latin.woff2")
    # same arguments as the pyftsubset command line
    subset.main([os.path.join(FONTS,f"AktivGrotesk_{stem}.woff2"),
                 f"--unicodes={UNICODES}","--layout-features=*",
                 "--flavor=woff2",f"--output-file={out}"])
    subsets[stem]=out

# ---- fonts/laio-fonts-inline.css ----
INLINE_HEAD="""/* LA.IO Aktiv Grotesk, embedded.
   Light 300, Regular 400 and Bold 700, subset to Latin, as base64 woff2 data URIs.
   Nothing here makes a network request.

   Use it where external fonts are blocked: claude.ai artifacts, Claude Design,
   Lovable previews, email builders. Paste this whole file into a <style> tag
   in the page, then set font-family: 'Aktiv Grotesk', sans-serif.
   On a real site, link https://assets.la.io/fonts/laio-fonts.css instead.

   Generated by _build/build_fonts.py. Do not edit by hand. To regenerate:
     pip3 install fonttools brotli
     python3 _build/build_fonts.py
*/
"""
blocks=[]
for stem in INLINE_CUTS:
    b64=base64.b64encode(open(subsets[stem],"rb").read()).decode("ascii")
    blocks.append(face(f"data:font/woff2;base64,{b64}",WEIGHT[stem],"normal"))
inline_css=INLINE_HEAD+"\n"+"\n".join(blocks)
INLINE=os.path.join(FONTS,"laio-fonts-inline.css")
write(INLINE,inline_css)

# ---- fonts/laio-fonts.css ----
HOSTED_HEAD="""/* LA.IO Aktiv Grotesk, hosted.
   All nine cuts at the full character set: Thin 100, Light 300, Regular 400,
   SemiBold 600, Bold 700, and italics of Thin, Light, Regular and Bold.

   On any real site, link it once:
     <link rel="stylesheet" href="https://assets.la.io/fonts/laio-fonts.css">
   then set font-family: 'Aktiv Grotesk', sans-serif.
   Browsers download only the weights a page uses.

   Sandboxed previews that block assets.la.io, such as claude.ai artifacts,
   need laio-fonts-inline.css instead.

   Generated by _build/build_fonts.py. Do not edit by hand.
*/
"""
HOSTED=os.path.join(FONTS,"laio-fonts.css")
write(HOSTED,HOSTED_HEAD+"\n"+"\n".join(face(f"{HOST}AktivGrotesk_{stem}.woff2",w,s) for stem,w,s in CUTS))

# ---- _build/font-test.html ----
# Each column is its own iframe document. Both CSS files declare the same family,
# so in one document the later @font-face would win and both columns would match.
# The fallback is monospace so a font that fails to load is obvious.
COLUMN="""<!doctype html>
<html><head><meta charset="utf-8">
__FONTS__
<style>
body{margin:0;padding:32px;background:#01233C;color:#fff;font-family:'Aktiv Grotesk',monospace;-webkit-font-smoothing:antialiased}
h1{font-size:44px;line-height:1.05;margin:0 0 16px;letter-spacing:-0.01em}
.lt{font-weight:300}.bd{font-weight:700}
p{font-weight:400;font-size:17px;line-height:1.5;margin:24px 0 0;max-width:34em}
.pillars{font-size:22px}
.brackets{font-weight:700;font-size:40px;color:#63DCDE}
.status{font-family:monospace;font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:#63DCDE;margin-top:32px}
</style></head><body>
<h1 class="lt">Founders build companies in Louisiana.</h1>
<h1 class="bd">Founders build companies in Louisiana.</h1>
<p>The Louisiana Innovation Office backs founders with capital, coaching and connections. This paragraph is Regular 400 at body size. Numerals 0123456789, &ldquo;quotes&rdquo;, &lsquo;apostrophes&rsquo;, &euro;, &trade; and an ellipsis&hellip;</p>
<p class="pillars">+ Capital  + Coaching  + Connections</p>
<p class="brackets">&lt; LA.IO &gt;</p>
<div class="status" id="status">Checking fonts</div>
<script>
document.fonts.ready.then(function(){
  var w=[];document.fonts.forEach(function(f){if(f.family.replace(/["']/g,"")==="Aktiv Grotesk"&&f.status==="loaded")w.push(f.weight)});
  document.getElementById("status").textContent="Aktiv Grotesk loaded: "+(w.length?w.sort().join(" "):"none, showing fallback");
});
</script>
</body></html>
"""
hosted_col=COLUMN.replace("__FONTS__",'<link rel="stylesheet" href="../fonts/laio-fonts.css">')
inline_col=COLUMN.replace("__FONTS__","<style>\n"+inline_css+"</style>")
TEST="""<!doctype html>
<!-- Font delivery check for fonts/laio-fonts.css and fonts/laio-fonts-inline.css.
     Generated by _build/build_fonts.py. Not linked from any page. Do not edit by hand.

     Left:  <link> to ../fonts/laio-fonts.css, which pulls the full woff2s from
            https://assets.la.io/fonts/. The left column only works over http, not file://.
     Right: the contents of laio-fonts-inline.css in a <style> tag. Works anywhere.

     From the repo root:
       python3 -m http.server 8000
       open http://localhost:8000/_build/font-test.html
-->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Aktiv Grotesk delivery test</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@500&display=swap">
<style>
body{margin:0;padding:32px 16px;background:#01233C;color:#fff}
.label{font-family:'JetBrains Mono',monospace;font-weight:500;font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:#63DCDE;margin:0 0 12px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;max-width:1400px;margin:0 auto}
iframe{display:block;width:100%;height:620px;border:1px solid #00B9FE;border-radius:0}
@media (max-width:800px){.grid{grid-template-columns:1fr}}
</style></head><body>
<div class="grid">
<div><p class="label">Hosted / fonts/laio-fonts.css</p><iframe id="hosted" title="Hosted CSS" srcdoc="__HOSTED__"></iframe></div>
<div><p class="label">Inline / fonts/laio-fonts-inline.css</p><iframe id="inline" title="Inline CSS" srcdoc="__INLINE__"></iframe></div>
</div>
</body></html>
"""
TEST_PATH=os.path.join(ROOT,"_build","font-test.html")
write(TEST_PATH,TEST.replace("__HOSTED__",html.escape(hosted_col,quote=True))
                    .replace("__INLINE__",html.escape(inline_col,quote=True)))

# ---- report ----
print("Built:")
for stem in INLINE_CUTS: size(subsets[stem])
inline_bytes=size(INLINE)
size(HOSTED)
size(TEST_PATH)
if inline_bytes>INLINE_LIMIT:
    sys.exit(f"FAIL: {os.path.relpath(INLINE,ROOT)} is {inline_bytes:,} bytes, over the {INLINE_LIMIT:,} byte limit.")
